titre: |
  Calcul du revenu du travailleur indépendant ou dirigeant d'entreprise après paiement des cotisations et de l'impôt sur le revenu.

objectifs:
  - salarié . rémunération . net . à payer avant impôt
  - dirigeant . rémunération . nette
  - dirigeant . auto-entrepreneur . net de cotisations
  - protection sociale . retraite
  - protection sociale . retraite . base . trimestres
  - protection sociale . santé . indemnités journalières

questions:
  liste noire:
    - entreprise . charges
    - entreprise . activité . libérale . réglementée
  liste:
    - entreprise . activité
unité par défaut: €/an
situation:
  dirigeant . régime social: "'auto-entrepreneur'"
  entreprise . activité . mixte: non
  salarié . ATMP . taux réduit: oui
