objectifs:
  - contrat salarié . prix du travail
  - contrat salarié . rémunération . brut de base . équivalent temps plein
  - contrat salarié . rémunération . brut de base
  - contrat salarié . rémunération . net
  - contrat salarié . rémunération . net après impôt

questions:
  à l'affiche:
    Temps partiel: contrat salarié . temps de travail . temps partiel
    Emploi franc: contrat salarié . aides employeur . emploi franc . éligible
    Cadre: contrat salarié . statut cadre
    Heures supplémentaires: contrat salarié . temps de travail . heures supplémentaires
    Titres-restaurant: contrat salarié . frais professionnels . titres-restaurant
    Impôt: impôt . méthode de calcul
    Commune: établissement . localisation
  non prioritaires:
    - contrat salarié . frais professionnels
    - contrat salarié . rémunération . avantages en nature
    - entreprise . association non lucrative
    - entreprise . non assujettie à TVA
    - contrat salarié . statut JEI
    - contrat salarié . complémentaire santé
    - contrat salarié . régime des impatriés
unité par défaut: €/mois
situation:
  dirigeant: non
  entreprise . catégorie juridique: non
  contrat salarié . activité partielle: non
  impôt . méthode de calcul . par défaut:
    # On utilise le taux neutre qui est plus rapide à calculer et qui correspond
    # à une fiche de paie pour laquelle le taux effectif n'est pas connu
    # (employeur qui n'a pas reçu de taux de la DGFiP ou bien jeune qui démarre
    # un premier travail). cf #1121
    #
    # Pour les hauts revenus le barème au taux neutre pose problème car il
    # provoque des effets de seuils importants (voir #1661). On revient donc à
    # la méthode “au barème” par défaut pour les hauts revenus. La valeur de
    # 6000 €/mois correspond au seuil où les tranches du barème neutre
    # augmentent par paliers de 4% ou 5%.
    variations:
      - si: contrat salarié . rémunération . brut de base <= 6000 €/mois
        alors: "'taux neutre'"
      - sinon: "'barème standard'"
