objectifs:
  - ic√¥ne: üë©‚Äçüíº
    nom: Mon revenu
    objectifs:
      - contrat salari√© . r√©mun√©ration . total
      - contrat salari√© . cotisations
      - contrat salari√© . r√©mun√©ration . net
      - imp√¥t
      - contrat salari√© . r√©mun√©ration . net apr√®s imp√¥t
  - ic√¥ne: üè¢
    nom: Mon entreprise
    objectifs:
      - entreprise . charges
      - entreprise . chiffre d'affaires minimum

questions:
  √† l'affiche:
    ACRE: entreprise . ACRE
    Commune: √©tablissement . localisation
    Imp√¥t sur le revenu: imp√¥t . m√©thode de calcul
    Indemnit√© v√©lo: contrat salari√© . indemnit√© kilom√©trique v√©lo . active
  liste noire:
    - contrat salari√© . r√©mun√©ration . avantages en nature
    - entreprise . charges
    - entreprise . r√©mun√©ration du dirigeant
    - entreprise . association non lucrative
  non prioritaires:
    - entreprise . √©tablissement bancaire
    - entreprise . effectif
    - √©tablissement . localisation
    - entreprise . ratio alternants
    - contrat salari√© . compl√©mentaire sant√©
    - contrat salari√© . r√©gime des impatri√©s

unit√© par d√©faut: ‚Ç¨/an
situation:
  dirigeant: "'assimil√© salari√©'"
