objectifs:
  - icÃ´ne: ğŸ‘©â€ğŸ’¼
    nom: Mon revenu
    objectifs:
      - dirigeant . rÃ©munÃ©ration totale
      - dirigeant . indÃ©pendant . cotisations et contributions
      - dirigeant . indÃ©pendant . revenu net de cotisations
      - dirigeant . indÃ©pendant . revenu professionnel
      - impÃ´t
      - revenu net aprÃ¨s impÃ´t
  - icÃ´ne: ğŸ¢
    nom: Mon entreprise
    objectifs:
      - entreprise . charges
      - entreprise . chiffre d'affaires minimum

questions:
  Ã  l'affiche:
    Type d'activitÃ©: entreprise . catÃ©gorie d'activitÃ©
    Date de crÃ©ation: entreprise . date de crÃ©ation
    ACRE: entreprise . ACRE
    ImpÃ´t sur le revenu: impÃ´t . mÃ©thode de calcul
  liste noire:
    - entreprise . charges
  liste:
    - entreprise
    - Ã©tablissement
    - dirigeant . indÃ©pendant
    - situation personnelle
    - impÃ´t
  non prioritaires:
    - dirigeant . indÃ©pendant . IJSS
    - dirigeant . indÃ©pendant . cotisations et contributions . exonÃ©rations
    - entreprise . ZFU
    - entreprise . catÃ©gorie d'activitÃ© . dÃ©bit de tabac
unitÃ© par dÃ©faut: â‚¬/an
situation:
  dirigeant: "'indÃ©pendant'"
