objectifs:
  - ic√¥ne: üë©‚Äçüíº
    nom: Mon revenu
    objectifs:
      - contrat salari√© . r√©mun√©ration . total
      - contrat salari√© . cotisations
      - contrat salari√© . r√©mun√©ration . net
      - imp√¥t
      - contrat salari√© . r√©mun√©ration . net apr√®s imp√¥t
  - ic√¥ne: üè¢
    nom: Mon entreprise
    objectifs:
      - entreprise . charges
      - entreprise . chiffre d'affaires

questions:
  √† l'affiche:
    ACRE: entreprise . ACRE
    Commune: √©tablissement . localisation
    Avantages en nature: contrat salari√© . r√©mun√©ration . avantages en nature
    Imp√¥t sur le revenu: imp√¥t . m√©thode de calcul
    
  liste noire:
    - entreprise . charges
    - entreprise . r√©mun√©ration du dirigeant
    - entreprise . association non lucrative
  non prioritaires:
    - entreprise . non assujettie √† TVA
    - entreprise . effectif
    - √©tablissement . localisation
    - entreprise . ratio alternants
    - contrat salari√© . compl√©mentaire sant√©
    - contrat salari√© . r√©gime des impatri√©s

unit√© par d√©faut: ‚Ç¨/an
situation:
  dirigeant: "'assimil√© salari√©'"
  contrat salari√© . activit√© partielle: non #TODO : en attendant que la transitivit√© du remplacement soit impl√©ment√©e
