objectifs:
  - icÃ´ne: ğŸ‘©â€ğŸ’¼
    nom: Mon revenu
    objectifs:
      - dirigeant . rÃ©munÃ©ration . totale
      - dirigeant . rÃ©munÃ©ration . cotisations et contributions
      - dirigeant . rÃ©munÃ©ration . nette
      - dirigeant . rÃ©munÃ©ration . impÃ´t
      - dirigeant . rÃ©munÃ©ration . nette aprÃ¨s impÃ´t
  - icÃ´ne: ğŸ¢
    nom: Mon entreprise
    objectifs:
      - entreprise . chiffre d'affaires
      - entreprise . charges
      - entreprise . charges . rÃ©munÃ©ration dirigeant

questions:
  Ã  l'affiche:
    Type d'activitÃ©: entreprise . activitÃ©
    Date de crÃ©ation: entreprise . date de crÃ©ation
    ACRE: entreprise . ACRE
    Contrats Madelins: dirigeant . indÃ©pendant . contrats madelin
    Conjoint collaborateur: dirigeant . indÃ©pendant . conjoint collaborateur
    ImpÃ´t sur le revenu: impÃ´t . mÃ©thode de calcul
  liste noire:
    - entreprise . charges
  liste:
    - entreprise
    - Ã©tablissement
    - dirigeant . indÃ©pendant
    - situation personnelle
    - impÃ´t
  non prioritaires:
    - dirigeant . indÃ©pendant . IJSS
    - dirigeant . indÃ©pendant . cotisations et contributions . exonÃ©rations
    - entreprise . ZFU
    - entreprise . activitÃ© . dÃ©bit de tabac
unitÃ© par dÃ©faut: â‚¬/an
situation:
  dirigeant: "'indÃ©pendant'"
