objectifs:
  - entreprise . chiffre d'affaires
  - entreprise . charges
  - dirigeant . indépendant . cotisations et contributions
  - dirigeant . indépendant . revenu net de cotisations
  - impôt
  - revenu net après impôt

questions:
  liste noire:
    - entreprise . charges
  liste:
    - entreprise . activité
    - dirigeant . indépendant . PL . métier
    - entreprise . date de création
    - dirigeant . indépendant
    - entreprise
    - établissement
    - situation personnelle
    - impôt
  non prioritaires:
    - dirigeant . indépendant . contrats madelin
    - dirigeant . indépendant . IJSS
    - dirigeant . indépendant . cotisations et contributions . exonérations
    - dirigeant . indépendant . revenus étrangers
    - entreprise . ZFU
unité par défaut: €/an
situation:
  dirigeant: "'indépendant'"
  entreprise . activité: "'libérale'"
  entreprise . imposition: "'IR'"
