name: Publication du paquet publicodes
on:
  push:
    paths:
      - publicodes/**
      - .github/workflows/publish-publicodes.yaml

jobs:
  test:
    if: contains(join(github.event.commits.*.message, ' | '), 'ðŸ“¦ Publicodes v1.0.0-beta.')
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
    - run: yarn install --frozen-lockfile
    - working-directory: ./publicodes/example/publicode-react
      run: |
        yarn install
        yarn test

  publish:
    needs: test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
    - run: yarn install --frozen-lockfile
      env:
        NPM_TOKEN: ${{ secrets.NPM_PUBLISH_SECRET }}
    - working-directory: ./publicodes/core
      run: | 
        npm publish ${{ github.ref != 'refs/heads/master' && '--dry-run' || ''}}
        npm publish ${{ github.ref != 'refs/heads/master' && '--dry-run' || ''}} --tag next
    - working-directory: ./publicodes/ui-react
      run: |
        npm publish ${{ github.ref != 'refs/heads/master' && '--dry-run' || ''}}
        npm publish ${{ github.ref != 'refs/heads/master' && '--dry-run' || ''}} --tag next
